### ISSUE TITLE
Bring the map above the fold on the homepage

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#103]
It could go next to the site description, although Princeton's layout was favored by some on the Interface Committee:
![princeton](https://user-images.githubusercontent.com/2367677/41615180-29da0916-73c0-11e8-9651-dceeab956799.png)

**Comment by ewlarson** [comment]
I would want to pursue this type of UI change after GeoBlacklight is updated to Blacklight 7.0 (still a release candidate right now). When that GBL update is released, we'll need migrate to it, and because BL 7.0 comes with support for the UI toolkit Bootstrap 4, we'll need to make updates to almost all of the view code in the Geoportal to support the new release of Bootstrap -- that work will provide a great window of opportunity to make significant updates to the design.

Also, for the record (again), I'm not a fan of GBL's map-based discovery. I don't think moving it above the fold does anything but amplify its UX issues.

**Comment by KarenMajewicz** [comment]
Should I push it back to Q4 (Oct-Dec) work then?

**Comment by ewlarson** [comment]
Not just yet. Let's wait and see how the summer code sprint goes.

**Comment by KarenMajewicz** [comment]
Maybe we can experiment with the map size and placement by doing design changes on dev followed by user testing before deciding.

**Comment by ewlarson** [comment]
![screen shot 2018-11-28 at 2 32 14 pm](https://user-images.githubusercontent.com/69827/49180597-b9667900-f31a-11e8-8690-10936cb2dc3a.png)
