### ISSUE TITLE
Feature clustering blocks attribute values

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#266]
When inspecting the web service for items with feature services, the attributes no longer show up. The clustering plugin may be blocking this.

**Comment by karenmajewicz** [comment]
This appears to be a different problem, not the clustering plugin. Closing.

**Comment by ewlarson** [comment]
https://geo.btaa.org/catalog/ab0f0408fcb5479e97df5a13d9a3c648_0

@karenmajewicz 

> Throwing this one in there:
> https://geo.btaa.org/catalog/ab0f0408fcb5479e97df5a13d9a3c648_0
> Querying these points also does not work, although I am not seeing a JS error. Maybe different problem?

This one does return an empty result set, so it's a good match with:
https://github.com/geoblacklight/geoblacklight/issues/717

**Comment by ewlarson** [comment]
GeoDev is running a [new version of feature_layer.js](https://github.com/BTAA-Geospatial-Data-Project/geoportal/commit/16148d2228f1d3194ca572dc824a451605ea6cc4) that fundamentally changes how data is displayed for markers. Instead of using the marker latlng and querying (by distance) for nearby properties, we're just adding a marker onclick handler to populate the attribute table with the data that arrives when the feature layers are initially requested -- using just one trip to the server for markers and properties, instead of one to draw markers and another to fetch properties.

Even clusters with many spider-fied points populate the attr table. 
https://geodev.btaa.org/catalog/77c3283978464432b9a391b8b9cf7885_0

<img width="1280" alt="Screen Shot 2019-11-20 at 2 47 53 PM" src="https://user-images.githubusercontent.com/69827/69276863-dab41b00-0ba4-11ea-808a-dcd38f2857ca.png">

Ohio addresses example works, too.
https://geodev.btaa.org/catalog/ab0f0408fcb5479e97df5a13d9a3c648_0
<img width="1280" alt="Screen Shot 2019-11-20 at 2 49 56 PM" src="https://user-images.githubusercontent.com/69827/69277001-16e77b80-0ba5-11ea-9275-72abe02b8c32.png">

@karenmajewicz Can you please check these examples out? Let me know if you think there is any downside to switching to this technique to load the marker data.

**Comment by karenmajewicz** [comment]
These seems to be an acceptable solution for now. 

I will run it by a few Task Forcers to see if they think we need to have the clustered points spread to their exact locations.
