### ISSUE TITLE
Troubleshoot blank values

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#327]
Blank values are now showing up in the facets and item view pages for this collection only: https://geo.btaa.org/?f[dct_isPartOf_sm][]=05d-01 Not sure yet if it is a processing error or something different about the application.

**Comment by ewlarson** [comment]
I see empty values in dc_subjects: 
```
 "dc_subject_sm": [
    ""
  ],
```

**Comment by karenmajewicz** [comment]
This is new behavior. I regularly upload records with empty/null values to Solr, but, in the past, they either did not get indexed or did not display in the application.

**Comment by ewlarson** [comment]
Well... this issue is _odd_.

Solr has always allowed a blank or empty string ("") to be a _valid_ facet value. We should have seen this issue a long time ago if we were pushing empty strings into facets:

```json
  "dct_spatial_sm": [
    ""
  ],
```

HOWEVER, Solr ignores null values in json for facets. So this is the right way to index empty facet values:

```json
  "dct_spatial_sm": [
    null
  ],
```

Any chance your python scripts started outputting empty strings instead of null recently?

**Comment by ewlarson** [comment]
If we encounter this issue in GEOMG:
https://github.com/sciencehistory/scihist_digicoll/pull/514/commits/5b2d6e4356d07661abec5991cfdd65c8fd5c43e6

**Comment by karenmajewicz** [comment]
Thank you for troubleshooting! I have tested it and it looks like the problem was with my latest Python script that publishes records to Solr.
