### ISSUE TITLE
Update SVG thumbnails that do not display.

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#347]
We have a set of items with thumbnails that are in the SVG format. (https://geo.btaa.org/catalog?f%5Bdct_isPartOf_sm%5D%5B%5D=999-0004) Although the images were "successfully" harvested, they do not appear in the interface. I replaced the SVGs with JPGs. However, the application is not re-harvesting. How can I re-trigger this?

**Comment by ewlarson** [comment]
Currently, you can remove a batch of sidecar images via a rake task and a CSV file of document ids/slugs:
https://github.com/geoblacklight/geoblacklight_sidecar_images#remove-a-batch

We must have used this at some point. There is some additional info in the code here:
https://github.com/geoblacklight/geoblacklight_sidecar_images/blob/develop/lib/tasks/geoblacklight_sidecar_images_tasks.rake#L173-L184

Ultimately, this is another example of an issue where you need more control over document imagery: running a harvest, rejecting results, adding additional images, removing images, etc.

**Comment by karenmajewicz** [comment]
[simply.csv](https://github.com/BTAA-Geospatial-Data-Project/geoportal/files/6442910/simply.csv)

These are the IDs for the 12 items that need the thumbnail removed.

**Comment by ewlarson** [comment]
I'm seeing that these items still have an SVG image for their b1g_image_ss value. From https://geo.btaa.org/catalog/999-0004-109/admin:

```
"b1g_image_ss" => "https://simplyanalytics.com/wp-content/uploads/2015/08/sa_logo_white.svg"
```

ActiveStorage doesn't support SVG images out-of-the-box, because SVGs are text files, and thus a potential XSS vector. So! We should update all these items to use an image file. We should also work to add images management tooling into GEOMG.
