### ISSUE TITLE
Fix rollover text on resource class icons

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#387]
When hovering over these icons, the text that comes up is duplicated. For example, the text is "imageryImagery". Maybe the text is coming from 2 different places?

**Comment by mberkowski** [comment]
It looks like the SVGs are ending up with two `<title>` elements because our .svg images in `app/assets/images/blacklight/` already have hard-coded elements like `<title>maps</title>` but then the Blacklight icon class cracks open the svg markup and sets a title-case title element of its own witout checking for an existing one. https://github.com/projectblacklight/blacklight/blob/865fa6f8d71e048db29d363261ad3cab274ca07e/app/models/blacklight/icon.rb#L26-L31

```
<svg version="1.1" width="32" height="32" viewBox="0 0 32 32" role="img"><title>Maps</title>
  <title>maps</title>
  <path .....
```

**Comment by ewlarson** [comment]
This are NOT fixed. GeoDev shows the duplicated title. I am stumped... somewhere it is picking up an older SVG icon with a title element inside it.

**Comment by karenmajewicz** [comment]
update: resource type icons are still displaying with doubled rollover text.

**Comment by mberkowski** [comment]
Clearing the Rails cache in production seems to have cleared this up. You can reopen if you are still seeing it after a hard refresh in your browser.

**Comment by karenmajewicz** [comment]
Thank you - this is working now!
