### ISSUE TITLE
Filter for Dataset and Image

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#44]
As we add more maps and begin to add inks to interactive geoservices, we need a way to differentiate them in the interface.  A new facet called "Resource Type" that pulls from dc_type (currently unused in the interface) could help. The main [DCMI values](http://dublincore.org/documents/dcmi-type-vocabulary/#H7) to use here would be Dataset, Image (or Still Image), and Service.

To minimize confusion, the "Data Type" facet could be renamed to "Geometry Type," which is a better reflection of its usage.

**Comment by ewlarson** [comment]
A couple quick questions here:

* Where should this new facet be displayed in the order of facets?  Seems rather useful, so higher up the list?
* "Dataset" and "Image" are quite clear to me, but I don't know what "Service" means.  Is that the best name/label here?

**Comment by KarenMajewicz** [comment]
Since it is a higher level of categorization, I can imagine it being second, above data type.  If the GBL community likes it, maybe it could have icons as well.

Dataset, image, and service come from the Dublin Core values, but they might not be obvious to people.  

Image in this case would always be a scanned map.  

Service would mean something like Web App.  This would be a resource that you don't just download, but a website you visit to analyze info.  [Here's some examples. ](https://gisdata.mn.gov/dataset?res_format=WebApp) I don't know how many services we would add, but we have a few sites in mind.

**Comment by ewlarson** [comment]
Okay, adding this facet is trivial, but we have some metadata cleanup to make this facet work well.  Looks like we have 1,826 records with "Still image" and 391 records with "Still Image".

Do you want to collapse those values to one consistent form before I push this into the codebase?

**Comment by KarenMajewicz** [comment]
I have not paid much attention to this element in the past, so I'll do some cleanup this week.  I will comment again when they are done.

**Comment by KarenMajewicz** [comment]
The Metadata Committee approved this facet for production.

**Comment by KarenMajewicz** [comment]
Change this to look for multiple field: dc_type_sm

**Comment by ewlarson** [comment]
In production with release 1.8.12
